### ISSUE TITLE
notworking with LXD Snap package

### ISSUE THREAD

**Issue by mutwakel** [AdaptiveScale/lxdui#3]
hi ,
i have used with LXD Snap package AND ITS NOT WORKIN

**Comment by vhajdari** [comment]
Hi @mutwakel, thanks for reporting the issue.  I've only done some preliminary testing with the LXD snap package and I'm able to replicate the issue.  Need to do a little investigation into the differences between the version installed by the package manager and snap.

**Comment by mutwakel** [comment]
hi @vhajdar,
I really appreciate the effort you have put in on this project. you have done wonderful work in contributing your talents and skills to the project. I'm looking forward to seeing what you can achieve in the future.
Thanks for the great work .

**Comment by stephen-d-hill** [comment]
Now that the LXD team have deprecated their PPA, snapd is the only way of getting the latest version of LXD. I am especially stuck as I'm on 14.04.

**Comment by vhajdari** [comment]
LXDUI is currently undergoing a rewrite with Python 3 and will be released
as a Snap package as well.  You can use the backports if you wanna stay on
14.04.


Regards,

Tony Hajdari

**Comment by stephen-d-hill** [comment]
I am already using trusty-backports version of lxd
```
$ lxd --version
2.0.11
```
but I get the following when trying to connect via Firefox browser:

```
$ sudo lxdui -d -p 5555
[sudo] password for stephen:
================================
APP_SECRET_KEY = s3cr3tk3y1
================================
Starting lxdui v1.0.1 on port 5555   
--------------------------------
DEBUG feature: ON
--------------------------------
Credentials: admin:admin> !
================================
 * Running on http://0.0.0.0:5555/
 * Restarting with reloader
================================
APP_SECRET_KEY = s3cr3tk3y1
================================
Starting lxdui v1.0.1 on port 5555
--------------------------------
DEBUG feature: ON
--------------------------------
Credentials: admin:admin> !
================================
192.168.10.180 - - [13/Feb/2018 19:07:04] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/lxdui/app.py", line 202, in home
    return render_template("login.html")
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 132, in render_template
    ctx.app.update_template_context(context)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 764, in update_template_context
    context.update(func())
  File "/usr/local/lib/python2.7/dist-packages/lxdui/app.py", line 110, in get_lxc_version
    ver = float((output_rez).strip())
```

**Comment by vhajdari** [comment]
lxdui is being rewritten to run as a snap, and all the sudo commands contained in 1.0 are being removed.  Please use version 2.0 for snap compatibility.

**Comment by quamis** [comment]
still not working:
![lxdui](https://user-images.githubusercontent.com/2966084/87660371-9b57c180-c767-11ea-9562-61552f2f3b34.png)

Am I missing someting?

**Comment by quamis** [comment]
my bad. My user wasn't in the `lxd` group
