### ISSUE TITLE
Cert create fails

### ISSUE THREAD

**Issue by dp1140a** [AdaptiveScale/lxdui#302]
I am running this on Ubuntu 18.04 as a systemd service
In trying to create new certs I get the following error:

> sudo lxdui cert create
Traceback (most recent call last):
  File "/usr/local/bin/lxdui", line 11, in <module>
    load_entry_point('LXDUI==2.1.2', 'console_scripts', 'lxdui')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/LXDUI-2.1.2-py3.6.egg/app/cli/cli.py", line 249, in create
    c.save(key)
TypeError: save() missing 1 required positional argument: 'data'

**Comment by ailegion** [comment]
@dp1140a I will test this and get back to you

**Comment by wccropper** [comment]
Just installed and having the same issues with cert creation.

**Comment by jetroni** [comment]
This has been fixed.
