### ISSUE TITLE
Create Certificates on Centos 7

### ISSUE THREAD

**Issue by daniejstriata** [AdaptiveScale/lxdui#319]
Hi,

I installed LXD on a Centos 7 server and compiled lxdui on it. I have gcc and openssl-devel installed. When I try to generate certificates I get the following:
```
# lxdui cert create 
Traceback (most recent call last):
  File "/opt/lxdui/lxdui-python3/bin/lxdui", line 11, in <module>
    load_entry_point('LXDUI==2.1.2', 'console_scripts', 'lxdui')()
  File "/opt/lxdui/lxdui-python3/lib64/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/opt/lxdui/lxdui-python3/lib64/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/opt/lxdui/lxdui-python3/lib64/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/lxdui/lxdui-python3/lib64/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/lxdui/lxdui-python3/lib64/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/lxdui/lxdui-python3/lib64/python3.6/site-packages/click-6.7-py3.6.egg/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/opt/lxdui/lxdui-python3/lib64/python3.6/site-packages/LXDUI-2.1.2-py3.6.egg/app/cli/cli.py", line 249, in create
    c.save(key)
TypeError: save() missing 1 required positional argument: 'data'
```

**Comment by jetroni** [comment]
#302
