### ISSUE TITLE
something error while running

### ISSUE THREAD

**Issue by Dawn-Xu-helloworld** [AdaptiveScale/lxdui#379]
Traceback (most recent call last):
  File "/home/dawn/lxdui-2.1.3/run.py", line 1, in <module>
    from app.cli.cli import lxdui
  File "/home/dawn/lxdui-2.1.3/app/cli/cli.py", line 4, in <module>
    from app.cli.init import Init
  File "/home/dawn/lxdui-2.1.3/app/cli/init.py", line 1, in <module>
    from app.lib import conf, auth, cert
  File "/home/dawn/lxdui-2.1.3/app/lib/cert.py", line 2, in <module>
    from OpenSSL import crypto
  File "/home/dawn/lxdui-2.1.3/venv/lib/python3.11/site-packages/pyOpenSSL-17.5.0-py3.11.egg/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/home/dawn/lxdui-2.1.3/venv/lib/python3.11/site-packages/pyOpenSSL-17.5.0-py3.11.egg/OpenSSL/crypto.py", line 1550, in <module>
    class X509StoreFlags(object):
  File "/home/dawn/lxdui-2.1.3/venv/lib/python3.11/site-packages/pyOpenSSL-17.5.0-py3.11.egg/OpenSSL/crypto.py", line 1570, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'

**Comment by IdoitEngineer** [comment]
I was seeing the same error.  There is a pull request to update the requirement if you are an a python version > 3.10
I just grabbed the updated file and re-ran the setup.... Golden now!
https://github.com/AdaptiveScale/lxdui/pull/374

**Comment by jetroni** [comment]
We deeply apologize once again for the very late reply, #374 and #380 should fix this issue. PRs will be reviewed soon.
