### ISSUE TITLE
Authenticate failed

### ISSUE THREAD

**Issue by levin-kelevra** [AdaptiveScale/lxdui#4]
```
lxc --version
2.21
```
```
127.0.0.1 - - [21/Dec/2017 09:00:40] "POST /containers-list HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/flask_login/utils.py", line 228, in decorated_view
    return func(*args, **kwargs)
  File "/home/slevinkelevra/github.com/lxdui/lxdui/app.py", line 263, in containers_list
    IMAGE_OS = str(container.expanded_config["image.os"]).capitalize()
KeyError: 'image.os'
```
If I go from one definition to another, I see the following:
```
conn = Client()
    conn.authenticate('SUPERSECRETPASS')
```
I used this command to set password:
``lxc config set core.trust_password SUPERSECRETPASS``

And why Python2???

**Comment by vhajdari** [comment]
fixed in lxdui-2.0
